// @generated
// This file is automatically generated by Kanel. Do not modify manually.

import type { ColumnType, Selectable, Insertable, Updateable } from "kysely";

/** Identifier type for references */
export type ReferenceId = string & { __brand: "ReferenceId" };

/** Represents the table references */
export default interface ReferencesTable {
	id: ColumnType<ReferenceId, ReferenceId, ReferenceId>;

	symbol: ColumnType<string, string, string>;

	fullHash: ColumnType<string, string, string>;

	body: ColumnType<string, string, string>;

	summary: ColumnType<string, string, string>;

	createdAt: ColumnType<Date, Date | string | undefined, Date | string>;
}

export type Reference = Selectable<ReferencesTable>;

export type NewReference = Insertable<ReferencesTable>;

export type ReferenceUpdate = Updateable<ReferencesTable>;
