import type { Config } from "tailwindcss";

export default {
	darkMode: ["class"],
	content: ["./src/**/*.{js,jsx,ts,tsx}"],
	safelist: ["bg-green/10", "bg-red/10", "bg-blue/10"],
	theme: {
		extend: {
			fontFamily: {
				sans: [
					"Inter",
					"ui-sans-serif",
					"system-ui",
					"sans-serif",
					"Apple Color Emoji",
					"Segoe UI Emoji",
					"Segoe UI Symbol",
					"Noto Color Emoji",
				],
			},
			borderRadius: {
				lg: "var(--radius)",
				md: "calc(var(--radius) - 2px)",
				sm: "calc(var(--radius) - 4px)",
			},
			colors: {
				background: "hsl(var(--background))",
				foreground: "hsl(var(--foreground))",
				card: {
					DEFAULT: "hsl(var(--card))",
					foreground: "hsl(var(--card-foreground))",
				},
				popover: {
					DEFAULT: "hsl(var(--popover))",
					foreground: "hsl(var(--popover-foreground))",
				},
				primary: {
					DEFAULT: "hsl(var(--primary))",
					foreground: "hsl(var(--primary-foreground))",
				},
				secondary: {
					DEFAULT: "hsl(var(--secondary))",
					foreground: "hsl(var(--secondary-foreground))",
				},
				muted: {
					DEFAULT: "hsl(var(--muted))",
					foreground: "hsl(var(--muted-foreground))",
				},
				accent: {
					DEFAULT: "hsl(var(--accent))",
					foreground: "hsl(var(--accent-foreground))",
				},
				destructive: {
					DEFAULT: "hsl(var(--destructive))",
					foreground: "hsl(var(--destructive-foreground))",
				},
				border: "hsl(var(--border))",
				input: "hsl(var(--input))",
				ring: "hsl(var(--ring))",
				chart: {
					"1": "hsl(var(--chart-1))",
					"2": "hsl(var(--chart-2))",
					"3": "hsl(var(--chart-3))",
					"4": "hsl(var(--chart-4))",
					"5": "hsl(var(--chart-5))",
				},
				rosewater: "hsl(var(--rosewater))",
				flamingo: "hsl(var(--flamingo))",
				pink: "hsl(var(--pink))",
				mauve: "hsl(var(--mauve))",
				red: "hsl(var(--red))",
				maroon: "hsl(var(--maroon))",
				peach: "hsl(var(--peach))",
				yellow: "hsl(var(--yellow))",
				green: "hsl(var(--green))",
				teal: "hsl(var(--teal))",
				sky: "hsl(var(--sky))",
				sapphire: "hsl(var(--sapphire))",
				blue: "hsl(var(--blue))",
				lavender: "hsl(var(--lavender))",
				text: "hsl(var(--text))",
				"subtext-1": "hsl(var(--subtext-1))",
				"subtext-0": "hsl(var(--subtext-0))",
				"overlay-2": "hsl(var(--overlay-2))",
				"overlay-1": "hsl(var(--overlay-1))",
				"overlay-0": "hsl(var(--overlay-0))",
				"surface-2": "hsl(var(--surface-2))",
				"surface-1": "hsl(var(--surface-1))",
				"surface-0": "hsl(var(--surface-0))",
				base: "hsl(var(--base))",
				mantle: "hsl(var(--mantle))",
				crust: "hsl(var(--crust))",
				sidebar: {
					DEFAULT: "hsl(var(--sidebar-background))",
					foreground: "hsl(var(--sidebar-foreground))",
					primary: "hsl(var(--sidebar-primary))",
					"primary-foreground": "hsl(var(--sidebar-primary-foreground))",
					accent: "hsl(var(--sidebar-accent))",
					"accent-foreground": "hsl(var(--sidebar-accent-foreground))",
					border: "hsl(var(--sidebar-border))",
					ring: "hsl(var(--sidebar-ring))",
				},
			},
			fontSize: {
				xxs: "0.625rem", // 10px
			},
		},
	},
	plugins: [require("tailwindcss-animate")],
} satisfies Config;
